version: '3.8'

services:
  core_postgres:
    image: postgres:13
    restart: always
    container_name: core_postgres
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_password
      POSTGRES_DB: core_db
    ports:
      - "5437:5432"  # پورت سمت چپ رو هرچی دوست داری بذار (مثلا 5437)
    volumes:
      - core_postgres_data:/var/lib/postgresql/data

  core_redis:
    image: redis:7
    restart: always
    container_name: core_redis
    ports:
      - "6381:6379"

  core_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - core_postgres
      - core_redis

volumes:
  core_postgres_data:
